Update hyp.scratch-high.yaml
ERROR: File "/content/yolov9/utils/augmentations.py", line 248, in copy_paste
l, box, s = labels[j], boxes[j], segments[j]
IndexError: list index out of range

python command used to produce this error:
!python train.py --batch 16 --epochs 5 --img 640 --device 0 --min-items 0 --close-mosaic 2 --data /content/drive/MyDrive/Coding_central/WallDetection/yolov9-fork/dataset_wall2/data.yaml --weights {HOME}/weights/gelan-c.pt --cfg models/detect/gelan-c.yaml --hyp hyp.scratch-high.yaml

No changes to the command had to be made to resolve this error. Copy-past augmentation is disabled in this commit.